services:
    hoversprite-app:
        image: phucdoan2003/hoversprite-backend
        container_name: hoversprite-backend
        ports:
            - "8080:8080"
            - "8443:8443"
            - "9092:9092"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hoversprite
            SPRING_DATASOURCE_USERNAME: hoversprite_admin
            SPRING_DATASOURCE_PASSWORD: enterprisehd
            SERVER_PORT: 8443
            SERVER_SSL_KEY_STORE: /app/resources/keystore.p12
            SERVER_SSL_KEY_STORE_PASSWORD: changeit
            SERVER_SSL_KEY_ALIAS: tomcat
        volumes:
            - ./main/src/main/resources:/app/resources
        depends_on:
            - postgres
        healthcheck:
            test: ["CMD-SHELL", "curl -f https://localhost:8443/actuator/health || exit 1"]
            interval: 30s
            timeout: 10s
            retries: 5

    postgres:
        image: postgres:latest
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: hoversprite
            POSTGRES_USER: hoversprite_admin
            POSTGRES_PASSWORD: enterprisehd
        healthcheck:
            test: ["CMD-SHELL", "pg_isready hoversprite -U hoversprite_admin"]
            interval: 10s
            timeout: 5s
            retries: 5
