version: '3'
services:
    springboot-app:
        image: hoversprite-backend
        container_name: hoversprite-backend
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/hoversprite
            SPRING_DATASOURCE_USERNAME: hoversprite_admin
            SPRING_DATASOURCE_PASSWORD: enterprisehd
        depends_on:
            - postgres-db

    postgres-db:
        image: postgres:latest
        container_name: postgres-db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: hoversprite
            POSTGRES_USER: hoversprite_admin
            POSTGRES_PASSWORD: enterprisehd
